# lsi: false
title: Mats Eikeland Mollestad
author:
  name: Mats Eikeland Mollestad
  email: mats@mollestad.no
  description: An ML Engineer that tries to write some times
  contact:
  - title: linkedin
    url: https://www.linkedin.com/in/mats-e-mollestad/
  - title: github
    url: https://github.com/MatsMoll
  - title: email
    url: mailto:mats@mollestad
highlighter: rouge
markdown: kramdown
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
