lsi: false
title: Mats Eikeland Mollestad
email: mats@mollestad.no
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
